#define	_TYPE_A		1
#define	_TYPE_NS	2
#define _TYPE_MD	3
#define _TYPE_MF	4
#define	_TYPE_CNAME	5
#define	_TYPE_SOA	6
#define	_TYPE_MB	7
#define	_TYPE_MG	8
#define	_TYPE_MR	9
#define	_TYPE_NULL	10
#define	_TYPE_WKS	11
#define	_TYPE_PTR	12
#define	_TYPE_MX	15
#define	_TYPE_TXT	16
#define	_TYPE_RP	17
#define	_TYPE_AFSDB	18
#define	_TYPE_X25	19
#define	_TYPE_ISDN	20
#define	_TYPE_RT	21
#define	_TYPE_NSAP	22
#define	_TYPE_NSAPPTR	23
#define	_TYPE_SIG	24
#define	_TYPE_KEY	25
#define	_TYPE_PX	26
#define	_TYPE_GPOS	27
#define	_TYPE_AAAA	28
#define	_TYPE_LOC	29
#define	_TYPE_NXT	30
#define	_TYPE_EID	31
#define	_TYPE_NIMLOC	32
#define	_TYPE_SRV	33
#define	_TYPE_ATMA	34
#define	_TYPE_NAPTR	35
#define	_TYPE_KX	36
#define	_TYPE_CERT	37
#define	_TYPE_A6	38
#define	_TYPE_DNAME	39
#define	_TYPE_SINK	40
#define	_TYPE_OPT	41
#define	_TYPE_APL	42
#define	_TYPE_DS	43
#define	_TYPE_SSHFP	44
#define	_TYPE_IPSECKEY	45
#define	_TYPE_RRSIG	46
#define	_TYPE_NSEC	47
#define	_TYPE_DNSKEY	48
#define	_TYPE_DHCID	49
#define	_TYPE_NSEC3PARAM	50
#define	_TYPE_TLSA	51
#define	_TYPE_HIP	55
#define	_TYPE_HINFO	56
#define	_TYPE_RKEY	57
#define	_TYPE_TALINK	58
#define	_TYPE_CDS	59
#define	_TYPE_CDNSKEY	60
#define	_TYPE_OPENPGPKEY	61
#define	_TYPE_CSYNC	62
#define	_TYPE_SPF	99
#define	_TYPE_UINFO	100
#define	_TYPE_UID	101
#define	_TYPE_GID	102
#define	_TYPE_UNSPEC	103
#define	_TYPE_NID	104
#define	_TYPE_L32	105
#define	_TYPE_L64	106
#define	_TYPE_LP	107
#define	_TYPE_EUI48	108
#define	_TYPE_EUI64	109
#define _TYPE_TKEY	249
#define _TYPE_TSIG	250
#define _TYPE_IXFR	251
#define _TYPE_AXFR	252
#define _TYPE_MAILB	253
#define _TYPE_MAILA	254
#define _TYPE_ANY	255
#define _TYPE_CAA	257

#define	_CLASS_IN	1
#define	_CLASS_CH	3
#define	_CLASS_HS	4
#define _CLASS_ANY  255

int str2type(char *str);
int str2rcode(char *str);
int str2class(char *str);
long long str2unixlltime(char *str);
